Dim oAsmDef As AssemblyDocument
oDoc = ThisApplication.ActiveDocument
oPath = ThisDoc.Path

'Create File Open Dialogue
oDoc = ThisDoc.Document
Dim oFileDlg As Inventor.FileDialog = Nothing
InventorVb.Application.CreateFileDialog(oFileDlg)
oFileDlg.Filter = "Excel files (*.xls)(*.xlsx)|*.xls;*.xlsx"
oFileDlg.InitialDirectory = oPath

'Show File Open Dialogue
oFileDlg.DialogTitle = "Pick Lattice File"
oFileDlg.ShowOpen()
LatticeFile = oFileDlg.FileName

GoExcel.Open(LatticeFile, "Sheet1")

LastRow = 2
ENDTEST1 = GoExcel.CellValue("A" & LastRow)

While ENDTEST1 <> ""
	LastRow = LastRow + 1
	ENDTEST1 = GoExcel.CellValue("A" & LastRow)
End While

oProgBar = ThisApplication.CreateProgressBar(False, LastRow-2, "Component Placement Progress")

Dim i As Integer = 2
Dim length As Double
Dim short_length As String
Dim tag As String
Dim name As String
Dim type As String
Dim partname As String
ENDTEST = GoExcel.CellValue("A" & i)



While ENDTEST <> ""
	
	name = GoExcel.CellValue("B" & i) & "_" & GoExcel.CellValue("A" & i)
	type = GoExcel.CellValue("I" & i)
	length = GoExcel.CellValue("J" & i) * 1000
	angle = GoExcel.CellValue("K" & i) * (360 / (2 * PI))
	angle = Abs(angle)
	short_length = Floor(length)
	short_angle = Floor(angle)
	
	If type = "Sbend" Then
		partname = oPath & "\" & type & short_length & "_" & short_angle & ".ipt"
	Else
		partname = oPath & "\" & type & short_length & ".ipt"
	End If
	
	Dim pointA = ThisDoc.Geometry.Point(0,0,0)
	Dim componentA = Components.Add(name, partname, position := pointA, grounded := False, visible := True, appearance := Nothing)
	
	Constraints.AddUcsToUcs(name, "UCSs:1", name, name, "UCS1")
	
	oProgBar.Message = "Placing: " + name + ": " + CStr(i) + " of " + CStr(LastRow-1) + " components."
	oProgBar.UpdateProgress
	
	i = i + 1
	ENDTEST = GoExcel.CellValue("A" & i)
	
End While

oProgBar.Close

MessageBox.Show("Finished", "Progress")
