'Define Part type (key) as in Lattice File
key = "Sbend"

opath = ThisDoc.Path
Dim ReadCSV As New System.IO.StreamReader(ThisDoc.Path & "\cooler.layout_table")
Dim Elements As New ArrayList()

Do While ReadCSV.Peek <> -1
Elements.Add(ReadCSV.ReadLine.Split("	"))
Loop

Dim i As Integer = 1
Dim length As Double
Dim tag As String


For i=1 To Elements.Count-1
	
	tag = Elements(i)(8)
	length = Elements(i)(9) * 1000
	angle = Elements(i)(10) * (360 / (2 * PI))
	absangle = Abs(angle)
	
	If tag = key Then
		Parameter("Length") = length
		Parameter("Angle") = absangle
		
		If angle > 0 Then
			Parameter("d54") = 90
			ThisDoc.Document.SaveAs(oPath & "\" & tag & CStr(Floor(length)) & "_" & CStr(Floor(absangle)) & ".ipt", True)
		Else
			Parameter("d54") = -90
			ThisDoc.Document.SaveAs(oPath & "\" & tag & CStr(Floor(length)) & "_" & CStr(Floor(absangle)) & "M" & ".ipt", True)
		End If			
	End If
	
Next