oPath = ThisDoc.Path
GoExcel.Open(oPath & "/cooler.layout_table.xlsx", "cooler")

LastRow = 2
ENDTEST1 = GoExcel.CellValue("A" & LastRow)

While ENDTEST1 <> ""
	LastRow = LastRow + 1
	ENDTEST1 = GoExcel.CellValue("A" & LastRow)
End While

oProgBar = ThisApplication.CreateProgressBar(False, LastRow - 2, "Component Placement Progress")

Dim i As Integer = 2
Dim x_pos As Double
Dim y_pos As Double
Dim z_pos As Double
Dim length As Double
Dim short_length As String
Dim theta As Double
Dim phi As Double
Dim psi As Double
Dim tag As String
Dim name As String
Dim type As String
Dim partname As String
Dim dPi = Atan(1) * 4
Dim oXAxis As UnitVector
Dim oYAxis As UnitVector
Dim oZAxis As UnitVector
Dim oMatrix = ThisDoc.Geometry.Matrix()
Dim oRotateMatrix = ThisDoc.Geometry.Matrix()

ENDTEST = GoExcel.CellValue("A" & i)



While ENDTEST <> "" 

	name = GoExcel.CellValue("B" & i) & "_" & GoExcel.CellValue("A" & i)
	type = GoExcel.CellValue("I" & i)
	length = GoExcel.CellValue("J" & i) * 1000
	angle = GoExcel.CellValue("K" & i) * (360 / (2 * PI))
	short_length = Floor(length)
	short_angle = Floor(Abs(angle))

	If type = "Sbend" Then
		If angle > 0 Then
			partname = oPath & "\" & type & short_length & "_" & short_angle & ".ipt"
		Else
			partname = oPath & "\" & type & short_length & "_" & short_angle & "M" & ".ipt"
		End If
	Else
		partname = oPath & "\" & type & short_length & ".ipt"
	End If

	X = GoExcel.CellValue("C" & i) * 1000
	Y = GoExcel.CellValue("D" & i) * 1000
	Z = GoExcel.CellValue("E" & i) * 1000
	phi = -GoExcel.CellValue("G" & i) '* 180 / dPi
	theta = GoExcel.CellValue("F" & i) '* 180 / dPi
	psi = GoExcel.CellValue("H" & i) '* 180 / dPi

	Dim pointA = ThisDoc.Geometry.Point(X, Y, Z)
	
	'Rotation Matrix
	Dim X1 = Cos(theta)*Cos(psi)+Sin(theta)*Sin(psi)*Sin(phi)
	Dim X2 = Sin(psi)*Cos(phi)
	Dim X3 = Cos(theta)*Sin(psi)*Sin(phi)-Sin(theta)*Cos(psi)
	Dim vectorX = ThisDoc.Geometry.Vector(X1, X2, X3)
	Dim Y1 = Sin(theta)*Cos(psi)*Sin(phi)-Cos(theta)*Sin(psi)
	Dim Y2 = Cos(psi)*Cos(phi)
	Dim Y3 = Sin(theta)*Sin(psi)+Cos(theta)*Cos(psi)*Sin(phi)
	Dim vectorY = ThisDoc.Geometry.Vector(Y1, Y2, Y3)
	Dim Z1 = Sin(theta)*Cos(phi)
	Dim Z2 = -Sin(phi)
	Dim Z3 = Cos(theta)*Cos(phi)
	Dim vectorZ = ThisDoc.Geometry.Vector(Z1, Z2, Z3)
	Dim matrixA = ThisDoc.Geometry.Matrix()
	matrixA.SetCoordinateSystem(pointA, vectorX.AsUnitVector, vectorY.AsUnitVector, vectorZ.AsUnitVector)

	Dim componentA = Components.Add(name, partname, position := matrixA, grounded := True, visible := True, appearance := Nothing)



	oProgBar.Message = "PlacingComponents: " + name + ": #" + CStr(i) + " of " + CStr(LastRow - 2) + " UCSs."
	oProgBar.UpdateProgress

	i = i + 1

	ENDTEST = GoExcel.CellValue("A" & i)


End While

oProgBar.Close

'MessageBox.Show("Finished", "Progress")

'zoom all
ThisApplication.ActiveView.Fit